[2020-05-25 10:48:15,623] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 10:48:20,683] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin/ HTTP/1.1" 200 72816
[2020-05-25 10:48:44,044] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_calculation/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2403, in relay_calculation
    bandwidth3)
  File "D:\job\Relay_forecasting_Tool\apps\utils\zhongjidaikuan100GE.py", line 130, in band_100GE
    if T1 >= zs2:
TypeError: '>=' not supported between instances of 'int' and 'str'
[2020-05-25 10:48:44,076] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_calculation/ HTTP/1.1" 500 18591
[2020-05-25 10:50:57,119] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 10:51:00,917] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin/ HTTP/1.1" 200 72816
[2020-05-25 10:51:11,735] [views.py:2425] [views:relay_calculation] [INFO]- 不做方案对比
[2020-05-25 10:51:11,735] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_calculation/ HTTP/1.1" 200 51
[2020-05-25 10:53:31,884] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 10:54:09,232] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2458, in relay_compare
    sheet2 = excel.sheet_by_index(1)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlrd\book.py", line 466, in sheet_by_index
    return self._sheet_list[sheetx] or self.get_sheet(sheetx)
IndexError: list index out of range
[2020-05-25 10:54:09,255] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18490
[2020-05-25 11:03:33,444] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:03:33,617] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/images/favicon.ico HTTP/1.1" 200 4286
[2020-05-25 11:03:38,396] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:03:45,003] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlrd\book.py", line 474, in sheet_by_name
    sheetx = self._sheet_names.index(sheet_name)
ValueError: '中继方向' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2475, in relay_compare
    sheet = wb.sheet_by_name('中继方向')
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlrd\book.py", line 476, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <'中继方向'>
[2020-05-25 11:03:45,035] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18787
[2020-05-25 11:06:30,747] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:06:36,658] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:06:43,339] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2497, in relay_compare
    if '分省电路表' in sheets:
NameError: name 'sheets' is not defined
[2020-05-25 11:06:43,354] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18333
[2020-05-25 11:35:12,429] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:35:18,026] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:35:24,788] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2501, in relay_compare
    for i in range(2, len(dict) + 1):
TypeError: object of type 'type' has no len()
[2020-05-25 11:35:24,813] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18351
[2020-05-25 11:36:34,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:36:39,176] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:36:45,204] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2495, in relay_compare
    dict[nodes[i - 3] + '~' + nodes[j - 1]] = relay
IndexError: list index out of range
[2020-05-25 11:36:45,235] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18353
[2020-05-25 11:37:27,946] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:37:32,976] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:37:39,117] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2495, in relay_compare
    dict[nodes[i - 1] + '~' + nodes[j - 1]] = relay
IndexError: list index out of range
[2020-05-25 11:37:39,141] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 18353
[2020-05-25 11:39:01,411] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:39:04,748] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:39:11,671] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 11:50:03,933] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 11:50:11,431] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 11:50:17,484] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 17, in __init__
    self.__parser.formula()
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 81, in formula
    self.expr("V")
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 88, in expr
    self.prec0_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 133, in prec0_expr
    self.prec1_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 151, in prec1_expr
    self.prec2_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 181, in prec2_expr
    self.prec3_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 210, in prec3_expr
    self.prec4_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 228, in prec4_expr
    self.prec5_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 251, in prec5_expr
    self.primary(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 514, in primary
    arg_count=self.expr_list(arg_type_list, min_argc, max_argc)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 575, in expr_list
    self.expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 88, in expr
    self.prec0_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 133, in prec0_expr
    self.prec1_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 151, in prec1_expr
    self.prec2_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 181, in prec2_expr
    self.prec3_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 210, in prec3_expr
    self.prec4_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 228, in prec4_expr
    self.prec5_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 251, in prec5_expr
    self.primary(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 435, in primary
    self.match(REF2D)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1893, in match
    self._match_int(set)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1880, in _match_int
    self.tokenNames, self.LT(1), t, False, self.getFilename())
xlwt.antlr.MismatchedTokenException: <AST>:0:8:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2509, in relay_compare
    sh.write(i + 2, 2, Formula('SUM(C3:C)'), he_style3)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 22, in __init__
    raise ExcelFormulaParser.FormulaParseException("can't parse formula " + s)
xlwt.ExcelFormulaParser.FormulaParseException: can't parse formula SUM(C3:C)
[2020-05-25 11:50:17,535] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 21697
[2020-05-25 13:35:54,527] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:36:01,963] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:36:11,733] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 17, in __init__
    self.__parser.formula()
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 81, in formula
    self.expr("V")
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 88, in expr
    self.prec0_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 133, in prec0_expr
    self.prec1_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 151, in prec1_expr
    self.prec2_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 181, in prec2_expr
    self.prec3_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 210, in prec3_expr
    self.prec4_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 228, in prec4_expr
    self.prec5_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 251, in prec5_expr
    self.primary(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 514, in primary
    arg_count=self.expr_list(arg_type_list, min_argc, max_argc)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 575, in expr_list
    self.expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 88, in expr
    self.prec0_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 133, in prec0_expr
    self.prec1_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 151, in prec1_expr
    self.prec2_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 181, in prec2_expr
    self.prec3_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 210, in prec3_expr
    self.prec4_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 228, in prec4_expr
    self.prec5_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 251, in prec5_expr
    self.primary(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 435, in primary
    self.match(REF2D)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1893, in match
    self._match_int(set)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1880, in _match_int
    self.tokenNames, self.LT(1), t, False, self.getFilename())
xlwt.antlr.MismatchedTokenException: <AST>:0:8:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2509, in relay_compare
    sh.write(i + 2, 2, Formula('SUM(C3:C)'+str(len(dict)+2)), he_style3)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 22, in __init__
    raise ExcelFormulaParser.FormulaParseException("can't parse formula " + s)
xlwt.ExcelFormulaParser.FormulaParseException: can't parse formula SUM(C3:C)414
[2020-05-25 13:36:11,773] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 21722
[2020-05-25 13:37:33,653] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:37:39,101] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:37:48,161] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /CMNETwinUpload/relay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 17, in __init__
    self.__parser.formula()
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 81, in formula
    self.expr("V")
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 88, in expr
    self.prec0_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 133, in prec0_expr
    self.prec1_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 151, in prec1_expr
    self.prec2_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 181, in prec2_expr
    self.prec3_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 210, in prec3_expr
    self.prec4_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 228, in prec4_expr
    self.prec5_expr(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 251, in prec5_expr
    self.primary(arg_type)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormulaParser.py", line 515, in primary
    self.match(RP)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1893, in match
    self._match_int(set)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\antlr.py", line 1880, in _match_int
    self.tokenNames, self.LT(1), t, False, self.getFilename())
xlwt.antlr.MismatchedTokenException: <AST>:0:0:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\CMNETwinUpload\views.py", line 2509, in relay_compare
    sh.write(i + 2, 2, Formula('SUM(C3:C'+str(len(dict)+2))+')', he_style3)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlwt\ExcelFormula.py", line 22, in __init__
    raise ExcelFormulaParser.FormulaParseException("can't parse formula " + s)
xlwt.ExcelFormulaParser.FormulaParseException: can't parse formula SUM(C3:C414
[2020-05-25 13:37:48,195] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 500 20403
[2020-05-25 13:43:28,323] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:43:32,884] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:43:39,255] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:46:30,952] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:46:35,503] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:46:41,878] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:47:56,341] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:47:59,282] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:48:05,368] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:49:03,325] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:49:08,332] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /IPwinUpload/IPwin_2/ HTTP/1.1" 200 4402
[2020-05-25 13:49:14,385] [exception.py:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /IPwinUpload/iprelay_compare/
Traceback (most recent call last):
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\job\Relay_forecasting_Tool\apps\IPwinUpload\views.py", line 1536, in iprelay_compare
    wb = xlrd.open_workbook(path1, formatting_info=True)
  File "D:\job\Relay_forecasting_Tool\venv\lib\site-packages\xlrd\__init__.py", line 111, in open_workbook
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\job\\Relay_forecasting_Tool\\excel\\ipwin\\new_book.xls'
[2020-05-25 13:49:14,414] [basehttp.py:124] [basehttp:log_message] [ERROR]- "POST /IPwinUpload/iprelay_compare/ HTTP/1.1" 500 18644
[2020-05-25 13:49:39,560] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:49:45,894] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:52:12,460] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:52:12,595] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /static/images/favicon.ico HTTP/1.1" 200 4286
[2020-05-25 13:52:14,648] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:52:20,153] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 172
[2020-05-25 13:52:31,761] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:53:55,948] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:54:01,755] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:54:07,934] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 13:55:14,138] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 13:55:16,894] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 13:55:23,055] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 172
[2020-05-25 13:55:30,433] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
[2020-05-25 15:31:54,709] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 11505
[2020-05-25 15:32:01,995] [basehttp.py:124] [basehttp:log_message] [INFO]- "GET /CMNETwinUpload/CMNETwin_2/ HTTP/1.1" 200 4522
[2020-05-25 15:32:08,749] [basehttp.py:124] [basehttp:log_message] [INFO]- "POST /CMNETwinUpload/relay_compare/ HTTP/1.1" 200 63
